<?php
if(Mage::getStoreConfig('adwordsremarketing/adwordsremarketing_group/enable',Mage::app()->getStore()) == 1):

$pageIdentifier = Mage::app()->getFrontController()->getAction()->getFullActionName();

switch ($pageIdentifier) {
    case "catalog_category_view":
        $pageIdentifier = 'category';
        break;
    case "catalog_product_view":
        $pageIdentifier = 'product';
        $_product = Mage::registry('current_product');
        $_prodid = $_product->getSku();
        $_prodprice = number_format($_product->getPrice(), 2);        
        break;
    case "contacts_index_index":
        $pageIdentifier = 'siteview';
        break;
    case "cms_index_index":
        $pageIdentifier = 'home';
        break;
    case "cms_page_view":
        $pageIdentifier = 'siteview';
        break;
    case "checkout_cart_index":
        $pageIdentifier = 'cart';
        $cartTotal = number_format($this->helper('checkout/cart')->getQuote()->getGrandTotal(), 2);
        $_prodprice = $cartTotal;
        break;
    case "checkout_onepage_success": 
        $pageIdentifier = 'purchase';
        $order_details = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
        $_prodprice = number_format($order_details->subtotal, 2);
        break;    
    default:
        $pageIdentifier = 'siteview';
}
?>
<script type="text/javascript">
var google_tag_params = { 
ecomm_prodid: '<?=$_prodid ?>',
ecomm_pagetype: '<?=$pageIdentifier ?>',
ecomm_totalvalue: '<?=$_prodprice ?>',
};
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = <?=Mage::getStoreConfig('adwordsremarketing/adwordsremarketing_group/adwordsremarketing_input',Mage::app()->getStore())?>;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://googleads.g.doubleclick.net/pagead/viewthroughconversion/<?=Mage::getStoreConfig('adwordsremarketing/adwordsremarketing_group/adwordsremarketing_input',Mage::app()->getStore());?>/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<? endif;  ?>
